import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export const strings = new LocalizedStrings({
 "en-US":{
    phoneNumber : "Phone Number",
    Password : "Password",
    Login : "Log in",
    SignUp : "Sign up",
    username : "Username",
    firstName : "First Name",
    lastName : "Last Name",
    finish : 'Finish',
    phoneNumberErrorMin : "Phone number contains 10 characters",
    phoneNumberErrorNull : "Phone number can not be null",
    usernameErrorMin : "Username contains minumum 6 characters",
    usernameErrorNull : "Username can not be null",
    firstnameErrorNull : "First name can not be null",
    lastNameErrorNull : "Last name can not be null",
    passwordErrorNull : "Password can not be null",
    passwordErrorMin : "Password contains minumum 6 characters",
    homeScreen : "Home",
    GroupInformation : "Group Information",
    members : "Group Members",
    groupOwner : "Group Owner",
    others : "Others",
    follow :"Follow",
    unfollow : "Unfollow",
    createPost : "Create post",
    UserNotFound : "User not found",
    generalError : "There is an error try again later",
    UserFound : "User was found in the information you provided, Have you forgotten your password ?",
    createPostText : "You can write something so people nearby can see you",
    createPostSucceed : "Your post succeesfully created",
    createPostUnSucceed : "Post did not created, you can try again later",
    createPostErrorNull : "This area can not be null",
    createPostErrorMin : "This area contains minimum 3 characters",
 },
 en:{
    phoneNumber : "Phone Number",
    Password : "Password",
    Login : "Log in",
    SignUp : "Sign up",
    username : "Username",
    firstName : "First Name",
    lastName : "Last Name",
    finish : 'Finish',
    phoneNumberErrorMin : "Phone number contains 10 characters",
    phoneNumberErrorNull : "Phone number can not be null",
    usernameErrorMin : "Username contains minumum 6 characters",
    usernameErrorNull : "Username can not be null",
    firstnameErrorNull : "First name can not be null",
    lastNameErrorNull : "Last name can not be null",
    passwordErrorNull : "Password can not be null",
    passwordErrorMin : "Password contains minumum 6 characters",
    homeScreen : "Home",
    GroupInformation : "Group Information",
    members : "Group Members",
    groupOwner : "Group Owner",
    others : "Others",
    follow :"Follow",
    unfollow : "Unfollow",
    createPost : "Create post",
    UserNotFound : "User not found",
    generalError : "There is an error try again later",
    UserFound : "User was found in the information you provided, have you forgotten your password ?",
    createPostText : "You can write something so people nearby can see you",
    createPostSucceed : "Your post succeesfully created",
    createPostUnSucceed : "Post did not created, you can try again later",
    createPostErrorNull : "This area can not be null",
    createPostErrorMin : "This area contains minimum 3 characters",
 },
 tr: {
    phoneNumber : "Telefon Numarası",
    Password : "Şifre",
    Login : "Giriş Yap",
    SignUp : "Üye Ol",
    username : "Kullanıcı Adı",
    firstName : "İsim",
    lastName : "Soyisim",
    finish : 'Bitir',
    phoneNumberErrorMin : "Telefon numarası 10 karakter olmalı",
    phoneNumberErrorNull : "Telefon numarası boş olamaz",
    usernameErrorMin : "Kullanıcı ismi en az 6 karakter olmalı",
    usernameErrorNull : "Kullanıcı ismi boş olamaz",
    firstnameErrorNull : "İsim boş olamaz",
    lastNameErrorNull : "Soyisim boş olamaz",
    passwordErrorNull : "Şifre boş olamaz",
    passwordErrorMin : "Şifre en az 6 karakter olmalı",
    homeScreen : "Ana Sayfa",
    GroupInformation : "Grup Bilgileri",
    members : "Grup Katılımcıları",
    groupOwner : "Group Sahibi",
    others : "Diğerlerı",
    follow :"Takip et",
    unfollow : "Takipten çık",
    createPost : "Gönderi Oluştur",
    UserNotFound : "Böyle bir kullanıcı bulunamadı",
    generalError : "Bir hata meydana geldi, daha sonra tekrar deneyin",
    UserFound : "Verdiğiniz bilgilerde kullanıcı bulundu. Şifrenizi unutmuş olabilir misiniz?",
    createPostText : "Bir şeyler yazabilirsin böylece yakındaki insanlar seni görebilir",
    createPostSucceed : "Gönderiniz başarıyla oluşturuldu",
    createPostUnSucceed : "Gönderiniz oluşturalamadı. Lütfen sonra tekrar deneyin.",
    createPostErrorNull : "Bu alan boş olamaz",
    createPostErrorMin : "Bu alan en az 3 karater olmalı",

 }
});


export const errorMessages = [{key :"Login.Post.UserNotFound" , value :strings.UserNotFound} , {key : "Signup.Post.UserFound", value : strings.UserFound}]